### PR TITLE
[app][fix] skip add fileRef on exception

### PR DESCRIPTION
**Pull request by M3ssman**
Sorry for the inconvenience, but I need a fix for https://github.com/OCR-D/ocrd_fileformat/issues/10 ASAP ...

### CODE REVIEW

**Review by kba — CHANGES_REQUESTED** [review]
With the [latest master](https://github.com/UB-Mannheim/ocr-fileformat/compare/v0.3.2...master) of ocr-fileformat, errors in conversion will actually fail with non-zero exit. So I think it would be more robust to update ocr-fileformat and check exit code:

```sh
ocr-transform # [...]
if (( $? > 0 ));then
    ocrd log error 'Transformation failed [...]"
    continue
fi
ocrd log INFO "Transformation succeeded [...]
```

**Comment by M3ssman** [comment]
@kba I did a quick check right now, updating ocr-fileformat submodule to 61d336e5ddfa73c773a3c37bb563d86b2252b52a, which has the change included. It still prints the stacktrace in case of an exception and therefore the numerical comparisation doesn't work.

The Exception is thrown in case there was no text content found. This can happen anytime for covers, blank pages, illustrations, etc...

**Comment by M3ssman** [comment]
But something else: I'd like to turn off bash debugging, since it fills the logs. If one is really interested in running a script in debug, it could be done straight at call time.

**Comment by kba** [comment]
#14 is now released as v0.0.5, @M3ssman can you have a look and check whether this adresses all issues raised in this PR?

**Comment by M3ssman** [comment]
Yes, looks good to me.

**Pull request closed without merging**
